name: error_dashboard

services:
  client:
    build:
      context: ./ErrorDashboardClient/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - ./ErrorDashboardClient/client/.env.development.local    
  
  # server:
  #   build:
  #     context: ./ErrorDashboardServer/server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./ErrorDashboardServer/server/.env

  # db:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: error_dashboard
